#spring.datasource.url=jdbc:mysql://localhost:3306/facialemorecog
#spring.datasource.username=user_test
#spring.datasource.password=123
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true
#
#
#server.error.include-message=always
server:
  port: 8100
  tomcat:
    max-http-post-size: 20MB
    max-request-size: 20MB
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/fer
    username: root
    password: qwert12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect